version: "3.7"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    volumes:
      - ./dist/openapi.json:/usr/share/nginx/html/openapi.json
    environment:
      API_URL: openapi.json
    ports:
      - "8080:8080"
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8081:8080"
  swagger-watcher:
    build: ./swagger-watch
    container_name: "swagger-watcher"
    volumes:
      - .:/api_doc
      - /api_doc/swagger-watch/node_modules
    working_dir: /api_doc/swagger-watch
    command: 'node index.js'
